### ISSUE TITLE
Clans Enemy / Ally Remove Ability Not working

### ISSUE THREAD

**Issue by JammyVSGaming** [the-h-team/ClansPro#2]
When i try and do either "/clan enemy remove clanname" or "/clan ally remove clanname" it comes up with an internal error. I have made a fresh new instance of clans with the new update to test but im getting the same result.
![Error](https://user-images.githubusercontent.com/90290936/194050652-6ea4020b-88d4-4f0a-b1e6-e9f8965941ac.png)

**Comment by Hempfest** [comment]
Fixed in discord support.
